name: Build

on:
  push:
    branches: '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Check that gh CLI is installed
        run: gh --version

      - uses: yantantether/muffet-action
        
