name: CI
on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
